### ISSUE TITLE
Merge python script and bash script

### ISSUE THREAD

**Issue by laiviet** [massongit/word2vec2glove#1]
Hi,

I suggest to merge two of your script into one bash or python script. It would be better because they are very tiny code.

**Comment by massongit** [comment]
@laiviet Thank you for your proposal!
It's difficult to realize your proposal because I don't know how to convert Word2Vec model from text format to binary format with Bash command.

**Comment by laiviet** [comment]
There are two options:

1. The main script is python. You can call Linux command from that code using subprocess

2. The main script is bash. You can embed your python code into bash as the following example.
https://stackoverflow.com/questions/2189098/embedding-short-python-scripts-inside-a-bash-script

Hope this would help!

**Comment by massongit** [comment]
@laiviet I merged scripts (7fb8ed1).
